### ISSUE TITLE
release on conda-forge

### ISSUE THREAD

**Issue by casperdcl** [TomographicImaging/eqt#76]
- [x] add @casperdcl as maintainer on this repo
- [x] [transfer repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to @TomographicImaging
- [x] update build framework, metadata, CI/CD (#77)
- [x] code & metadata tidy (#79)
- [x] double-check related issues https://github.com/paskino/qt-elements/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+conda
- [x] release [v0.7.1](https://github.com/TomographicImaging/eqt/releases/tag/v0.7.1) including `sdist` (`*.tar.gz`) for conda builds
- [x] setup `conda-forge` (currently using https://anaconda.org/ccpi & https://github.com/paskino/qt-elements/blob/v0.7.0/.github/workflows/conda_build_and_publish.yml)
  + https://github.com/conda-forge/staged-recipes/pull/23597
  + https://github.com/conda-forge/eqt-feedstock
- [x] update docs (mention `{conda,mamba} install -c conda-forge eqt`, add badges) #83

**Comment by lauramurgatroyd** [comment]
I think we should add correct licensing headers, similar to what we have in CIL whilst we are doing all this

**Comment by casperdcl** [comment]
by licensing headers, do you mean e.g. at the top of each `*.py` file?

**Comment by casperdcl** [comment]
🤢 yuck. [Can we do at the bottom of the file or (better yet) not at all](https://youtu.be/FyCYva9DhsI?t=1954) because [copyright is automatic even without a statement](https://en.wikipedia.org/wiki/Berne_Convention)? One project-level licence file is more than enough. Happy to ~fight~ discuss :)

**Comment by lauramurgatroyd** [comment]
We had clear advice from the lawyers that we need the license headers like this:
https://github.com/TomographicImaging/CIL/blob/master/Wrappers/Python/cil/io/NEXUSDataReader.py

**Comment by casperdcl** [comment]
I have legal advice from IP lawyers stating the exact opposite (based on copyright laws, acts, case law, the Berne convention cited above, etc.)... Maybe a gewd discussion topic :)

I would be super interested in speaking to the lawyers you mention.
